name: fifo-opt
channels:
  - conda-forge
  - https://sharc-lab.github.io/LightningSim/repo
dependencies:
  - python=3.11
  - lightningsim=0.2.5
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - pymoo
  - ruff
  - mypy